{{- include "shipping.set.env.variables" . }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.config.serviceAccountName }}
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.env }}
{{- end }}
